src/api/globalSearch.ts
src/components/base/interacting/btn/btn.scss
src/components/pages/search/search.tsx
src/components/structure/interacting/navigation/navigation.scss
src/components/structure/interacting/navigation/navigation.tsx
src/components/structure/interacting/search-result-navigation/index.ts
src/components/structure/interacting/search-result-navigation/search-result-navigation.scss
src/components/structure/interacting/search-result-navigation/search-result-navigation.tsx
src/components/structure/interacting/search-result-navigation/translations.json
src/components/structure/interacting/search-sidebar/search-sidebar.scss
src/components/structure/interacting/search-sidebar/search-sidebar.tsx
src/components/structure/interacting/search-sidebar/translations.json
src/components/structure/visualizing/artefact-overview/artefact-overview.scss
src/store/domains/globalSearch.ts
src/style/000-abstracts/variables.scss
src/style/010-base/content.scss

Pagination has been added to the result page.
- minor changes in globalSearch in order to get a proper result list
- minor changes in sidebar to show search result information
---
Sorry ob des großen Commits. Wie immer bitte drüber schauen und mir dann Nachhilfe geben, bevorzugt am Mittwoch oder Donnerstag

feat: Added Pagination

---

src/api/globalSearch.ts
src/components/pages/search/search.tsx
src/components/structure/interacting/navigation/navigation.tsx
src/components/structure/interacting/navigation/translations.json
src/components/structure/visualizing/artefact-card/artefact-card.scss
src/components/structure/visualizing/artefact-card/artefact-card.tsx
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx
src/providers/StoreProvider.tsx
src/store/StoreContext.ts
src/store/domains/collection.ts
src/store/domains/globalSearch.ts
src/store/domains/ui.ts
src/store/index.ts

Hi, kannste da noch mal drauf gucken, bitte. Die Implementierung der setFav Toggles hab ich leider nicht besser hin bekommen ;)

Artefakte können gesammelt werden

---

.env
README.md
src/components/pages/search/search.tsx
src/components/structure/visualizing/artefact-overview/artefact-overview.scss

Hi, hab die BaseUrls mal in die Env gepackt.

M refactor baseurls

---

src/components/base/interacting/checkbox/checkbox.scss
src/components/base/interacting/checkbox/checkbox.tsx
src/components/structure/interacting/accordion/accordion.scss
src/components/structure/interacting/search-sidebar/search-sidebar.tsx
src/components/structure/interacting/tree-list/tree-list.scss
src/components/structure/interacting/tree-list/tree-list.tsx

Huhu, ich habe die Filter ein bissl anders gestaltet.

Style Tweaks Filter

---

src/api/globalSearch.ts
src/components/structure/visualizing/artefact-line/artefact-line.tsx

Sollte idealerweise erst gemerged und deployed werden, wenn folgender PR durch ist und gemerged wurde: https://github.com/lucascranach/cranach-api/pull/49

Entfernung aller Referenzen auf data_all

---

src/api/globalSearch.ts
src/components/base/interacting/btn/btn.scss
src/components/pages/dashboard/dashboard.tsx
src/components/structure/interacting/navigation/navigation.tsx
src/components/structure/visualizing/artefact-line/artefact-line.scss
src/components/structure/visualizing/artefact-overview/artefact-overview.scss
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx
src/store/domains/ui.ts
src/style/000-abstracts/mixins.scss
src/style/000-abstracts/variables.scss

Adjustments for KKL launch

---

src/api/globalSearch.ts
src/components/structure/interacting/search/search.scss
src/components/structure/interacting/search/search.tsx
src/components/structure/interacting/search/translations.json
src/store/domains/globalSearch.ts

Mit diesem PR werden die beiden Filter `Besten Werke` und `Katalog` eingeführt.
Damit beide Filter funktionieren können, müssen zuvor folgende PRs gemerged und ausgespielt werden:
https://github.com/lucascranach/cranach-docker/pull/6
https://github.com/lucascranach/cranach-api/pull/53

feat(filters): introduce new isBestOf and catalog filter

---

src/components/structure/interacting/secondary-navigation/secondary-navigation.scss

fixed sidebar recovery

---

src/components/structure/visualizing/artefact-card/artefact-card.scss
src/components/structure/visualizing/artefact-card/artefact-card.tsx
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx

Hi,
ich glaub die Implementierung ist nicht preisverdächtig. Bitte mal checken :)
Dank und Grüße, c

Kleine Verbesserung der Interaktion der Favorite icons

---

src/App.tsx
src/store/domains/routing.ts
src/store/domains/ui.ts
src/store/rootStore.ts

Logik zum Setzen und Auslesen der Sprache aus dem URL-Pfad in Store auslagert

Sprach-Logik in Stores auslagern

---

src/components/structure/interacting/my-cranach/my-cranach.tsx
src/components/structure/interacting/search/search.tsx
src/components/structure/interacting/secondary-navigation/secondary-navigation.tsx
src/store/StoreContext.ts
src/store/domains/ui.ts

Musste hierfür ein wenig die Art und Weise anpassen, wie die Sichtbarkeit von bestimmten Komponente in der Sidebar im Store gehalten wird.
Dadurch kommt es jetzt dazu, dass der Such-View (Suche u. Filter, myCranach), beim Aufklappen der Sidebar, die Aufklapp-Animation beschleunigt.
Vllt. müsste man generell die verschiedenen States im UI-Store aufräumen, die mit der Sidebar zusammenhängen.

feat(ui): store ui view state in localstorage: keep synced

---

src/components/base/visualizing/cloak/cloak.scss
src/components/base/visualizing/cloak/cloak.tsx
src/components/base/visualizing/cloak/index.ts
src/components/pages/dashboard/dashboard.tsx
src/components/structure/visualizing/artefact-overview/artefact-overview.scss
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx
src/store/domains/globalSearch.ts
src/store/domains/ui.ts
src/style/000-abstracts/mixins.scss
src/style/000-abstracts/variables.scss

Hi,
ich hab mal eine 1. Version von der Funktion "Anzahl der Bilder richtet sich nach der Größe" nur für die kleinen Kacheln gemacht. Da ist sicherlich noch Luft nach oben, aber ich wollte erstmal was haben, damit Gunnar nicht immer jammern muss :)
Guck doch mal drauf.
Danke! c

1st version of suitable tiles

---

src/api/globalSearch.ts

Adressiert Issue:
- https://github.com/lucascranach/cranach-search/issues/48

Freischaltung von Thesaurus-Filtern

---

src/components/pages/dashboard/dashboard.tsx
src/components/structure/interacting/search-result-navigation/search-result-navigation.tsx

Adressiert folgende Issues:
- https://github.com/lucascranach/cranach-search/issues/42
- https://github.com/lucascranach/cranach-search/issues/44

Navigation per Pfeiltasten

---

src/api/globalSearch.ts
src/components/base/interacting/btn/btn.scss
src/components/base/interacting/btn/btn.tsx
src/components/base/interacting/text-input/text-input.scss
src/components/structure/interacting/navigation/navigation.tsx
src/components/structure/interacting/search/search.scss
src/components/structure/interacting/search/search.tsx
src/components/structure/interacting/search/translations.json
src/store/domains/globalSearch.ts
src/store/domains/routing.ts
src/style/010-base/page.scss

Hi Jorge,
hab ein bisschen im Frontend aufgeräumt … eine Sache müsstest Du Dir bitte noch anschauen, bzw. implementieren … aber das sollten wir mal kurz besprechen. Ist mir etwas zu kompliziert via Text :)
Beste Grüße,
Christian

Design improvements

---

src/components/base/interacting/text-input/text-input.scss
src/components/structure/interacting/navigation/translations.json
src/components/structure/interacting/secondary-navigation/secondary-navigation.tsx

Hi, ich bin die PowerPoint noch mal durch gegangen und hab ein paar Kleinigkeiten gefixt.

Minor fixes 03

---

src/components/pages/dashboard/dashboard.tsx

fix: added trailing slash to URL

---

src/api/globalSearch.ts
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx

Diese Anpassung erst deployen, wenn folgende Änderung in der API zuvor deployed wurde: https://github.com/lucascranach/cranach-api/pull/104

feat(debug): output searchSortingNumber for objects through data-attrs

---

.env
README.md
package.json
src/components/base/visualizing/logo/logo.tsx
src/components/structure/interacting/search/search.scss

Hi,
hab nen Link auf die Startseite eingebaut … da gibts aber noch TS Gemecker. Könntest Du da bitte noch mal schauen.
https://github.com/lucascranach/cda-orga/issues/41
Außerdem hab ich einen Preview Kontext eingebaut, damit die Suche unter https://lucascranach/intern/search/ getestet werden kann.
Dank und Grüße,
Christian

Preview Context und Link auf die Startseite

---

src/components/structure/interacting/my-cranach/my-cranach.scss
src/components/structure/interacting/search/search.scss
src/style/010-base/page.scss

style: improved sidebar style

---

src/api/literature-references.ts
src/api/types.ts
src/components/pages/dashboard/dashboard.tsx
src/components/pages/dashboard/translations.json
src/components/structure/interacting/search-literature-references/index.ts
src/components/structure/interacting/search-literature-references/search-literature-references.scss
src/components/structure/interacting/search-literature-references/search-literature-references.tsx
src/components/structure/interacting/search-literature-references/translations.json
src/components/structure/interacting/search/search.tsx
src/components/structure/interacting/secondary-navigation/secondary-navigation.tsx
src/components/structure/visualizing/artefact-overview/artefact-overview.scss
src/components/structure/visualizing/artefact-overview/artefact-overview.tsx
src/components/structure/visualizing/artefact-table/artefact-table.scss
src/components/structure/visualizing/artefact-table/artefact-table.tsx
src/store/domains/lighttable.ts
src/store/domains/searchLiteratureReferences.ts
src/store/domains/ui.ts

Erst nach folgendem MR abarbeiten: https://github.com/lucascranach/cranach-search/pull/97

feat(literature-references): LiteratureReferences extension

---

src/components/pages/dashboard/dashboard.tsx
src/components/structure/interacting/search-archivals/search-archivals.scss
src/components/structure/interacting/search-archivals/search-archivals.tsx
src/components/structure/interacting/search-literature-references/search-literature-references.scss
src/components/structure/interacting/search-literature-references/search-literature-references.tsx
src/components/structure/interacting/search-result-navigation/search-result-navigation.tsx
src/components/structure/interacting/search-works/search-works.scss
src/components/structure/interacting/search-works/search-works.tsx
src/components/structure/interacting/secondary-navigation/secondary-navigation.tsx
src/components/structure/visualizing/artefact-table/artefact-table.scss
src/components/structure/visualizing/artefact-table/artefact-table.tsx
src/store/domains/lighttable.ts
src/store/domains/searchArchivals.ts
src/store/domains/searchLiteratureReferences.ts
src/store/domains/searchWorks.ts

Auch hier gerne von Commit zu Commit gehen, da jeder Commit eine "Unschönheit" korrigiert.

Korrektur einiger kleiner Unschönheiten

---

src/store/domains/routing.ts

workaround: add search path segment if it would be overwritten by lan guage segment

---

src/components/structure/interacting/navigation/translations.json
src/components/structure/interacting/search-works/search-works.tsx

-> [#130](https://github.com/lucascranach/cranach-search/issues/130)

[BUGFIX] typo, uneccessary alert
